This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (785 entries accepted, 0 rejected).
Sorting entries.........done (8556 comparisons).
Generating output file thesis.acr....done (273 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
